BOT_TOKEN = 'MTIwMTQ4MzIxNDcyOTAwNzE0NA.GrBIA0.2to-Dy7iSR7OoRBHm0yuUfcF1pOlnccl3EY61A'
YOUTUBE_API_KEY = 'AIzaSyDfEis1F2ZFGsOssyzTXXbSY6q5dhk_ydw'
BOT_PREFIX = '+'
EMBEDCOLOR = '0xF8AA2A'
# BOT_ACTIVITY_TYPE = watching
BOT_ACTIVITY_NAME = '+help'